[package]
name = "trump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
serenity = "0.11.0"
tokio = { version = "1.4.0", features = ["rt", "macros"] }
rand = "0.8.5"